language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # The SDK version used to compile your project
    - android-27
    - build-tools-27.0.3

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean assembleDebug --stacktrace