language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - android-27
    - build-tools-27.0.3

jdk:
  - oraclejdk8

script:
  - ./ICT4DNews/gradlew clean assembleDebug --stacktrace