language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - android-27
    - build-tools-27.0.3

jdk:
  - oraclejdk8

before_install:
  - pwd
  - ls -la
  - cd ICT4DNews
  - pwd
  - ls -la

script:
  - gradle build assembleDebug --stacktrace