name: Android CI

on: [push]

jobs:
  build:

    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Ktlint
      run: |
        cd ICT4DNews
        ./gradlew clean ktlintCheck --stacktrace
    - name: Tests
      run: |
        cd ICT4DNews
        ./gradlew clean testDebugUnitTest lint --stacktrace
    - name: buildDebug
      run: |
        cd ICT4DNews
        ./gradlew clean assembleDebug --stacktrace
