name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Ktlint
      run: |
        cd ICT4DNews
        ./gradlew clean ktlint -Pci --stacktrace
    - name: Tests
      run: |
        ./gradlew clean test lint --stacktrace
